//
//  Created by Ivano Bilenchi on 01/05/16.
//  Copyright © 2016-2020 SisInf Lab. All rights reserved.
//

#import <Foundation/Foundation.h>

/// Project version number for OWLAPI.
FOUNDATION_EXPORT double OWLAPIVersionNumber;

/// Project version string for OWLAPI.
FOUNDATION_EXPORT const unsigned char OWLAPIVersionString[];

#import "OWLAnonymousClassExpression.h"
#import "OWLAnonymousIndividual.h"
#import "OWLAxiom.h"
#import "OWLAxiomType.h"
#import "OWLBooleanClassExpression.h"
#import "OWLCardinalityRestriction.h"
#import "OWLClass.h"
#import "OWLClassAssertionAxiom.h"
#import "OWLClassAxiom.h"
#import "OWLClassExpression.h"
#import "OWLClassExpressionType.h"
#import "OWLDataFactory.h"
#import "OWLDeclarationAxiom.h"
#import "OWLDisjointClassesAxiom.h"
#import "OWLDLConstruct.h"
#import "OWLDLExpressivityChecker.h"
#import "OWLEntity.h"
#import "OWLEntityType.h"
#import "OWLEquivalentClassesAxiom.h"
#import "OWLIdentifiedEntity.h"
#import "OWLIndividual.h"
#import "OWLIndividualAxiom.h"
#import "OWLIRI.h"
#import "OWLLogicalAxiom.h"
#import "OWLLogicalEntity.h"
#import "OWLManager.h"
#import "OWLNamedIndividual.h"
#import "OWLNamedObject.h"
#import "OWLNamespace.h"
#import "OWLNAryAxiom.h"
#import "OWLNAryBooleanClassExpression.h"
#import "OWLNAryClassAxiom.h"
#import "OWLNodeID.h"
#import "OWLObject.h"
#import "OWLObjectAllValuesFrom.h"
#import "OWLObjectCardinalityRestriction.h"
#import "OWLObjectComplementOf.h"
#import "OWLObjectExactCardinality.h"
#import "OWLObjectIntersectionOf.h"
#import "OWLObjectMaxCardinality.h"
#import "OWLObjectMinCardinality.h"
#import "OWLObjectProperty.h"
#import "OWLObjectPropertyAssertionAxiom.h"
#import "OWLObjectPropertyAxiom.h"
#import "OWLObjectPropertyDomainAxiom.h"
#import "OWLObjectPropertyExpression.h"
#import "OWLObjectPropertyRangeAxiom.h"
#import "OWLObjectSomeValuesFrom.h"
#import "OWLOntology.h"
#import "OWLOntologyID.h"
#import "OWLOntologyManager.h"
#import "OWLProperty.h"
#import "OWLPropertyAssertionAxiom.h"
#import "OWLPropertyAssertionObject.h"
#import "OWLPropertyAxiom.h"
#import "OWLPropertyDomainAxiom.h"
#import "OWLPropertyExpression.h"
#import "OWLPropertyRange.h"
#import "OWLPropertyRangeAxiom.h"
#import "OWLQuantifiedObjectRestriction.h"
#import "OWLQuantifiedRestriction.h"
#import "OWLRDFVocabulary.h"
#import "OWLRestriction.h"
#import "OWLSubClassOfAxiom.h"
#import "OWLTransitiveObjectPropertyAxiom.h"
#import "OWLUnaryPropertyAxiom.h"
